import { StyleSheet } from "react-native";
import { Colors } from "../../constants/Colors";

export const getStyles = (scheme: "light" | "dark") => {
  const colors = Colors[scheme];
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    planListContent: { padding: 20, paddingBottom: 80 },
    pageTitle: {
      fontSize: 32,
      fontWeight: "bold",
      color: colors.text,
      paddingTop: 30,
      marginBottom: 20,
    },
    planCard: {
      backgroundColor: colors.card,
      padding: 20,
      borderRadius: 10,
      marginBottom: 15,
    },
    planCardTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 15,
    },
    planCardDaysContainer: {
      flexDirection: "row",
      justifyContent: "space-around",
    },
    planCardDay: {
      width: 30,
      height: 30,
      borderRadius: 15,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },
    planCardDaySelected: { backgroundColor: colors.primary },
    planCardDayText: { color: colors.subtleText, fontWeight: "bold" },
    planCardDayTextSelected: { color: "#FFF" },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 50,
    },
    emptyText: { fontSize: 18, fontWeight: "600", color: colors.text },
    emptySubText: {
      fontSize: 14,
      color: colors.subtleText,
      marginTop: 10,
    },
    fab: {
      position: "absolute",
      width: 56,
      height: 56,
      alignItems: "center",
      justifyContent: "center",
      right: 20,
      bottom: 105,
      backgroundColor: colors.primary,
      borderRadius: 28,
      elevation: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    modalOuterContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    modalBackdrop: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalContentContainer: {
      width: "90%",
      maxHeight: "60%",
      borderRadius: 20,
      overflow: "hidden",
      backgroundColor: colors.card,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalContent: {
      width: "100%",
      height: "100%",
    },
    modalScrollView: {
      width: "100%",
    },
    modalScrollContent: {
      paddingHorizontal: 20,
      paddingTop: 15,
      paddingBottom: 30,
    },
    createModalScrollContent: {
      paddingBottom: 30,
    },
    sectionSpacing: {
      marginBottom: 25,
    },
    itemSpacing: {
      marginBottom: 15,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 15,
    },
    editableTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: colors.text,
      backgroundColor: colors.background,
      padding: 10,
      borderRadius: 8,
      flex: 1,
    },
    modalTitle: { fontSize: 24, fontWeight: "bold", color: colors.text },
    editButton: { padding: 8 },
    saveButton: { padding: 8 },
    label: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
      marginTop: 20,
      marginBottom: 10,
      alignSelf: "flex-start",
    },
    input: {
      backgroundColor: colors.background,
      padding: 15,
      borderRadius: 10,
      fontSize: 16,
      color: colors.text,
      width: "100%",
    },
    placeholder: { color: colors.subtleText },
    daysContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
    },
    dayButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },
    dayButtonSelected: { backgroundColor: colors.primary },
    dayButtonText: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.text,
    },
    dayButtonTextSelected: { color: "#FFF" },
    workoutsHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    workoutItem: {
      backgroundColor: colors.background,
      padding: 15,
      borderRadius: 10,
      marginBottom: 10,
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    editableWorkoutText: {
      flex: 1,
      fontSize: 16,
      color: colors.text,
    },
    workoutText: { fontSize: 16, color: colors.text },
    addButton: {
      marginTop: 20,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    addButtonText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: "600",
    },
    deleteButton: {
      padding: 8,
      marginLeft: 10,
    },
    modalContentWrapper: {
      width: "90%",
      maxHeight: "80%",
      borderRadius: 20,
      overflow: "hidden",
      backgroundColor: colors.card,
    },
    modalContainerCenter: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalContentCenter: {
      width: "100%",
      maxHeight: "100%",
      padding: 20,
    },
    saveIconButton: { padding: 8 },
    saveIcon: { color: colors.primary },
    workoutInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 10,
      width: "100%",
    },
    workoutInput: {
      flex: 1,
      backgroundColor: colors.background,
      padding: 15,
      borderRadius: 10,
      fontSize: 16,
      color: colors.text,
    },
    deleteWorkoutButton: {
      padding: 8,
    },
    deletePlanButton: {
      marginTop: 20,
      backgroundColor: colors.destructive,
      padding: 15,
      borderRadius: 10,
      alignItems: "center",
    },
    deletePlanButtonText: {
      color: "#FFF",
      fontWeight: "bold",
      fontSize: 16,
    },
  });
};
